apiVersion: v2
name: socketio-server
description: A Helm chart for Socket.IO server with Redis adapter for Kubernetes
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - socketio
  - websocket
  - realtime
  - redis
maintainers:
  - name: kahanit