# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  images: |
    - name: os-shell
      image: docker.io/kahanit/os-shell:12
    - name: redis-cluster
      image: docker.io/kahanit/redis-cluster:8.4.0-r1
    - name: redis-exporter
      image: docker.io/kahanit/redis-exporter:1.80.1
  licenses: Apache-2.0
  tanzuCategory: service
apiVersion: v2
appVersion: 8.4.0
dependencies:
- name: common
  repository: oci://registry-1.docker.io/kahanit
  tags:
  - bitnami-common
  version: 2.31.7
description: Redis(R) is an open source, scalable, distributed in-memory cache for
  applications. It can be used to store and serve data in the form of strings, hashes,
  lists, sets and sorted sets.
home: https://bitnami.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/redis/img/redis-stack-220x234.png
keywords:
- redis
- keyvalue
- database
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: redis-cluster
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/redis-cluster
version: 1.0.1
