apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - socketio-deployment.yaml
  - services.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: socketio
  app.kubernetes.io/component: realtime

namespace: default  # Change to your namespace