# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  images: |
    - name: mongodb-exporter
      image: docker.io/kahanit/mongodb-exporter:0.47.2
    - name: mongodb-sharded
      image: docker.io/kahanit/mongodb-sharded:8.2.3-r1
    - name: os-shell
      image: docker.io/kahanit/os-shell:12
  licenses: Apache-2.0
  tanzuCategory: service
apiVersion: v2
appVersion: 8.2.3
dependencies:
- name: common
  repository: oci://registry-1.docker.io/kahanit
  tags:
  - bitnami-common
  version: 2.31.7
description: MongoDB(R) is an open source NoSQL database that uses JSON for data storage.
  MongoDB(TM) Sharded improves scalability and reliability for large datasets by distributing
  data across multiple machines.
home: https://bitnami.com
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/mongodb/img/mongodb-stack-220x234.png
keywords:
- mongodb
- database
- nosql
- cluster
- replicaset
- replication
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: mongodb-sharded
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/mongodb-sharded
version: 1.0.1
