apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: syncroze-tls
spec:
  dnsNames:
    - socketio.syncroze.com
  privateKey:
    rotationPolicy: Always
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: syncroze-tls