{{- if .Values.certificate.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.ingress.tls.secretName }}
  labels:
    {{- include "socketio.labels" . | nindent 4 }}
  annotations:
    # Ensure Certificate is created before other resources
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/resource-policy": keep
spec:
  dnsNames:
    - {{ .Values.ingress.host }}
  privateKey:
    rotationPolicy: {{ .Values.certificate.privateKey.rotationPolicy }}
  issuerRef:
    kind: {{ .Values.certificate.issuerRef.kind }}
    name: {{ .Values.certificate.issuerRef.name }}
  secretName: {{ .Values.ingress.tls.secretName }}
{{- end }}